import React from 'react'

const Empatizar = () => {
  return (
    <div name='empatizar' className='bg-[#FD9D24] p-5 mt-12 pb-20 drop-shadow-xl'>
      <div className='container mx-auto max-w-5xl'>
          <div className='pt-14 flex flex-col lg:flex-row h-auto md:space-x-6'>
              <div className='w-2/5 mb-4'>
                <h2 className='text-7xl text-white font-semibold'>EMPATIZAR</h2>
              </div>
              <div className='md:w-3/5 p-2 text-justify text-white'>
              LOREM IPSUM DOLOR SIT AMET CONSECTETUR ADIPISICING ELIT. AT ADIPISCI QUO VOLUPTAS COMMODI DEBITIS ASPERNATUR MOLESTIAE SAEPE LABORUM BLANDITIIS. BLANDITIIS, MINUS. PROVIDENT NAM CUM QUISQUAM NIHIL DOLORE CONSECTETUR, EAQUE AMET INVENTORE NEMO, SEQUI TEMPORE EXPEDITA NOBIS DISTINCTIO VOLUPTATES QUOS CONSEQUUNTUR EIUS. TEMPORIBUS IMPEDIT TENETUR NON ACCUSAMUS IURE IPSA. LABORE ALIQUID QUOD HIC, NON DISTINCTIO QUOS MINUS SIMILIQUE MOLESTIAS TEMPORE CONSEQUUNTUR DELENITI AUTEM ET ISTE VITAE, FUGA MAGNI CUMQUE PARIATUR VELIT NAM DELECTUS ASPERIORES CORPORIS REM. ASPERNATUR VOLUPTATUM DEBITIS LABORE CUPIDITATE ET TEMPORE RATIONE MOLESTIAE LABORIOSAM UT ITAQUE MODI, ALIQUID EOS CUMQUE VEL DELENITI ISTE VITAE PRAESENTIUM MAGNAM EARUM CORPORIS HARUM.
              </div>
          </div>
        </div>
    </div>
  )
}

export default Empatizar